const projectData = [
  {
    url: "Equestr-Conseil",
    img: "equestr-logo.jpg",
    color: "#f8b818",
    brand: "Equestr",
    client: "Nova Box",
    year: "2024",
    team: "Developed Single-handedly",
    description: "Equestr Conseils combines top people with hiring opportunities, providing personalized recruiting services to each client's specific needs. In a continuously changing industry, we focus on providing solutions that promote success, supported by a dedication to excellent service, honesty, and long-term partnerships.",
    website: "https://equestrconseils.ca/",
    multiImgs: ["equestr_1.png","equestr_2.png",
      "equestr_3.png","equestr_4.png",
      "equestr_5.png","equestr_6.png",
      "equestr_7.png","equestr_8.png",
      "equestr_9.png","equestr_10.png",
      "equestr_11.png","equestr_12.png",
      "equestr_13.png","equestr_14.png",
      "equestr_15.png",],
  },
  {
    url: "Vcard",
    img: "black-logo.jpg",
    color: "#982c29",
    brand: "Vcard",
    client: "Black Concept",
    year: "2023",
    team: "Joint effort with Black Concept",
    description: "A digital vCard platform that showcases professional profiles and contact information for easy sharing and networking.",
    website: "https://black-concept.ma/qr/amers",
    multiImgs: ["vcard_1.png","vcard_2.png",
      "vcard_3.png",
    ],
  },
  {
    url: "Parcado",
    img: "parcado-logo.jpg",
    color: "#f5c713",
    brand: "Parcado",
    client: "Black Concept",
    year: "2023",
    team: "Developed Single-handedly",
    description: "Parcado is a digital platform connecting independent drivers with clients, offering a streamlined service similar to Uber. The website enables users to fill out a form with key details like name, phone number, car ownership, and employment status, helping to facilitate easy and efficient connections.",
    website: "https://fouzariparc.com/",
    multiImgs: ["parcado_1.png","parcado_2.png",],
  },
  {
    url: "MarocVeg",
    img: "marocveg-logo.jpg",
    color: "#188045",
    brand: "MarocVeg",
    client: "Black Concept",
    year: "2023",
    team: "Developed Single-handedly",
    description: "MarocVeg Ltd is a trusted supplier of fresh fruits, vegetables, and herbs. We focus on quality and sustainability by sourcing products directly from local farmers in Morocco. Our commitment to high standards ensures that you receive fresh produce with minimal chemical use, making us a reliable choice for your needs.",
    website: "https://marocveg.com/",
    multiImgs: ["marocveg_1.png","marocveg_2.png",
      "marocveg_3.png","marocveg_4.png",
      "marocveg_5.png","marocveg_6.png",
      "marocveg_7.png","marocveg_8.png",
      "marocveg_9.png",
    ],
  },
  {
    url: "Vicio",
    img: "vicio-logo.jpg",
    color: "#faaf3b",
    brand: "Vicio",
    client: "Black Concept",
    year: "2023",
    team: "Developed Single-handedly",
    description: "Vicio provides a specific food service that prioritizes fresh, high-quality ingredients. Vicio combines creativity and tradition, serving freshly marinated chicken, exceptional burgers on handmade brioche buns, and signature San Sebastián cheesecake. Each dish is carefully created, providing a welcoming ambiance that shows a passion for outstanding cuisine.",
    website: "https://vicio.ma/",
    multiImgs: ["vicio_1.png","vicio_2.png",
      "vicio_3.png","vicio_4.png",
      "vicio_5.png","vicio_6.png",
      "vicio_7.png","vicio_8.png",
      "vicio_9.png","vicio_10.png",
    ],
  },
  {
    url: "HB-digital",
    img: "hbdigital-logo.jpg",
    color: "#117beb",
    brand: "HB Digital",
    client: "Black Concept",
    year: "2023",
    team: "Developed Single-handedly",
    description: "HB Digital is a creative advertising and marketing agency specializing in graphic design, digital printing, and industrial manufacturing. With extensive experience, it provides tailored solutions to meet clients' needs.\nNote: I developed the official website, but the server is currently down.",
    website: "https://hb-digital.ma/",
    multiImgs: ["hbdigital_1.png",],
}

];

export default projectData;
